### ISSUE TITLE
<Feature> Filter job based on Year of Experience (YOE)

### ISSUE THREAD

**Issue by kripa-sindhu-007** [kuutsav/leetcode-compensation#10]
It would be a great feature to have as most user would want to inquire only about those compensation that fall around their YOE regardless of the company. So to attract more users this can be implemented.

**Comment by kuutsav** [comment]
Had already planned for this. Will add it to the roadmap.

**Comment by Nik-git1** [comment]
Should we take input as a range of years for yoe ? like someone with 3 years of yoe, might find data for yoe 3 to 5 useful . Using an offset value can be useful as well , like yoe + offset(optional).

**Comment by kripa-sindhu-007** [comment]
Yes, YOE+offset would be the best option to consider.

**Comment by kuutsav** [comment]
@Nik-git1 I prefer the range. Look at https://www.levels.fyi/t/software-engineer/locations/india, they have a dropdown for filters, otherwise it will soon start to clutter.

**Comment by Nik-git1** [comment]
@kuutsav, do we have any parameters to convert yoe as job level(entry, principal, manager,etc.)? if that is in work , we can wait for this issue, else we have options to implement 1) Yoe 2) yoe+offset 3) yoe slider(would take up extra space though) for now. I am planning to take up this issue.

**Comment by kuutsav** [comment]
Added in #31
