### ISSUE TITLE
[feature] Add sort by compensation

### ISSUE THREAD

**Issue by shubham-100ms** [kuutsav/leetcode-compensation#11]
It would be nice to have a sort by compensation feature.

**Comment by kuutsav** [comment]
Had already planned for this. Will add it to the roadmap.

**Comment by BabuNamburi** [comment]
Added a pr for this 
https://github.com/kuutsav/leetcode-compensation/pull/13

**Comment by kuutsav** [comment]
Added in #21, thanks to @Nik-git1
