### ISSUE TITLE
Wrong data for ibm

### ISSUE THREAD

**Issue by abhinav1592** [kuutsav/leetcode-compensation#20]
E.g

https://leetcode.com/discuss/compensation/4945800

It is showing 93,60,000 where as it's one 0 less.

**Comment by abhinav1592** [comment]
![Screenshot_20240614_113331_Chrome](https://github.com/kuutsav/leetcode-compensation/assets/2583022/5d89e1db-e586-4bb8-b084-f369afffc30d)

**Comment by abhinav1592** [comment]
It's all 1 zero extra.

You might to fix the code and recaliberate the data.

**Comment by kuutsav** [comment]
Thanks for the raising the issue. I'm aware that parsing using smaller (relatively) llms was bound to be inaccurate sometimes.

There is not much to be done here other than manually cleanup such instances when reported. If it was possible to confidently parse salaries without llms I would taken that route (already tried this with regex and it's very messy).

Btw, you can raise a PR to fix these cases as well. Look at the data folder.

**Comment by kuutsav** [comment]
Addressed in this [commit](https://github.com/kuutsav/leetcode-compensation/commit/e2eaf9a938d2ece1ef1a6f6ef21bccb7fe1b6ad1)
